=== Denisprosim/Restaurace-XML/restaurace-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:xmisd01:restaurant" 
    xmlns="urn:xmisd01:restaurant"
    xmlns:r="urn:xmisd01:restaurant"
    elementFormDefault="qualified">
    
    <xs:element name="restaurant" type="restaurantType">
        
        <xs:key name="chefTypeKey">
            <xs:selector xpath="r:menu/r:chef"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="menuTypeKey">
            <xs:selector xpath="r:menu"/>
            <xs:field xpath="@day"/>
        </xs:key>
        
        <xs:key name="alergensTypeKey">
            <xs:selector xpath="r:list_of_alergens/r:alergens/r:alergen"/>
            <xs:field xpath="@number"/>
        </xs:key>
        
        <xs:keyref refer="alergensTypeKey" name="alergenTypeKey">
            <xs:selector xpath="r:menu/r:food/r:alergens/r:alergen"></xs:selector>
            <xs:field xpath="@number"></xs:field>
        </xs:keyref>
        
    </xs:element>
    
    <xs:complexType name="restaurantType">
        <xs:sequence>
            <xs:element name="restaurant_name" type="xs:string"/>
            <xs:element name="adress" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="zip" type="zipType"/>
            <xs:element name="tel_number" type="tel_numberType"/>
            <xs:element name="opening_time" type="xs:time"/>
            <xs:element name="closing_time" type="xs:time"/>
            <xs:element name="menu" type="menuType" maxOccurs="unbounded"/>
            <xs:element name="list_of_alergens" type="list_of_alergensType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="zipType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}\s\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tel_numberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}\s\d{3}\s\d{3}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="menuType">
        <xs:sequence>
            <xs:element name="chef" type="chefType"/>
            <xs:element name="course" type="courseType" maxOccurs="3"/>
        </xs:sequence>
        <xs:attribute name="day" type="dayType"/>
    </xs:complexType>
    
    <xs:simpleType name="dayType">
        <xs:restriction base="xs:date">
            <xs:minInclusive value="2021-12-01"></xs:minInclusive>
            <xs:maxExclusive value="2022-12-31"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="chefType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
    
    <xs:complexType name="courseType">
        <xs:sequence>
            <xs:element name="food" type="foodType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="courseAttType"/>
    </xs:complexType>
    
    <xs:simpleType name="courseAttType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="appetizer"/>
            <xs:enumeration value="main"/>
            <xs:enumeration value="dessert"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="foodType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:float">
                            <xs:attribute name="currency" type="currencyType" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="alergens" type="alergensType"/>
            <xs:element name="calories" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CZK"/>
            <xs:enumeration value="USD"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="alergensType">
        <xs:sequence>
            <xs:element name="alergen" type="alergenType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="alergenType">
        <xs:sequence>
            <xs:element name="contains" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="number" type="xs:int"/>
    </xs:complexType>
    
    <xs:complexType name="list_of_alergensType">
        <xs:sequence>
            <xs:element name="alergens" type="alergensType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== Denisprosim/Restaurace-XML/restaurant 1.xml
<?xml version="1.0" encoding="UTF-8"?>
<restaurant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:xmisd01:restaurant restaurace-schema.xsd" xmlns="urn:xmisd01:restaurant">
    <restaurant_name>Bumbo</restaurant_name>
    <adress>Dlouhá 12</adress>
    <city>Praha</city>
    <zip>110 00</zip>
    <tel_number>987 277 835</tel_number>
    <opening_time>12:00:00</opening_time>
    <closing_time>17:00:00</closing_time>
    
    <menu day="2021-12-24">
        <chef id="1">
            <name>Ronaldo</name>
            <surname>Discrete</surname>
        </chef>
        <course type="appetizer">
            <food>
                <name>Brokolicový krém</name>
                <price currency="CZK">40</price>
                <description>Polévka z brokolice se špetkou soli</description>
                <alergens>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                    <alergen number="10">
                        <contains>Hořčice</contains>
                    </alergen>
                </alergens>
                <calories>230</calories>
            </food>
            <food>
                <name>Bramboračka</name>
                <price currency="CZK">39</price>
                <description>Polévka s bramborou a cibulí</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="10">
                        <contains>Hořčice</contains>
                    </alergen>
                </alergens>
                <calories>200</calories>
            </food>
        </course>
        <course type="main">
            <food>
                <name>Kuřecí steak s fazolovými lusky</name>
                <price currency="CZK">129</price>
                <description>Kuřecí steak s fazolovými lusky na slanině s grenaillemi</description>
                <alergens>
                    <alergen number="10">
                        <contains>Hořčice</contains>
                    </alergen>
                </alergens>
                <calories>420</calories>
            </food>
            <food>
                <name>Vepřové kostky s rýží</name>
                <price currency="CZK">119</price>
                <description>Vepřové kostky na znojemský způsob s dušenou rýží</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                </alergens>
                <calories>480</calories>
            </food>
            <food>
                <name>Smažený karbanátek s bramborovou kaší</name>
                <price currency="CZK">110</price>
                <description>Smažený karbanátek s bramborovou kaší a kyselou okurkou</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="3">
                        <contains>Korýši</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                </alergens>
                <calories>470</calories>
            </food>
        </course>
        <course type="dessert">
            <food>
                <name>Belgické Waffle</name>
                <price currency="CZK">89</price>
                <description>Belgické vafle se spoustou pravého javorového sirupu</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                </alergens>
                <calories>240</calories>
            </food>
            <food>
                <name>Štrůdl</name>
                <price currency="CZK">49</price>
                <description>Babiččin štrůdl se skořicí a čerstvými jablky</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="6">
                        <contains>Sója</contains>
                    </alergen>
                </alergens>
                <calories>290</calories>
            </food>
            <food>
                <name>Palačinky</name>
                <price currency="CZK">99</price>
                <description>Palačinky s vanilkovou zmrzlinou a kousky ovoce</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                </alergens>
                <calories>350</calories>
            </food>
        </course>
    </menu>
    <menu day="2021-12-25">
        <chef id="2">
            <name>Marko</name>
            <surname>Polo</surname>
        </chef>
        <course type="appetizer">
            <food>
                <name>Květáková polévka</name>
                <price currency="CZK">40</price>
                <description>Polévka z květáku a cibule</description>
                <alergens>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                    <alergen number="10">
                        <contains>Hořčice</contains>
                    </alergen>
                </alergens>
                <calories>220</calories>
            </food>
            <food>
                <name>Žampiónová polévka</name>
                <price currency="CZK">59</price>
                <description>Polévka se žampióny a zeleninou</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                    <alergen number="9">
                        <contains>Celer</contains>
                    </alergen>
                </alergens>
                <calories>200</calories>
            </food>
        </course>
        <course type="main">
            <food>
                <name>Kuřecí steak na grilované zelenině</name>
                <price currency="CZK">139</price>
                <description>Kuřecí steak na grilované zelenině se sázeným vejcem a
                    grenaillemi</description>
                <alergens>
                    <alergen number="10">
                        <contains>Hořčice</contains>
                    </alergen>
                </alergens>
                <calories>420</calories>
            </food>
            <food>
                <name>Špagety aglio olio</name>
                <price currency="CZK">119</price>
                <description>Špagety aglio olio s parmskou šunkou a parmazánem</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="3">
                        <contains>Korýši</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                </alergens>
                <calories>450</calories>
            </food>
            <food>
                <name>Vepřové medailonky</name>
                <price currency="CZK">139</price>
                <description>Vepřové medailonky s česnekem a bramborovými rosty</description>
                <alergens>
                    <alergen number="10">
                        <contains>Hořčice</contains>
                    </alergen>
                </alergens>
                <calories>490</calories>
            </food>
        </course>
        <course type="dessert">
            <food>
                <name>Belgické Waffle</name>
                <price currency="CZK">89</price>
                <description>Belgické vafle se spoustou pravého javorového sirupu</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="7">
                        <contains>Mléko</contains>
                    </alergen>
                </alergens>
                <calories>240</calories>
            </food>
            <food>
                <name>Štrůdl</name>
                <price currency="CZK">49</price>
                <description>Babiččin štrůdl se skořicí a čerstvými jablky</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="6">
                        <contains>Sója</contains>
                    </alergen>
                </alergens>
                <calories>290</calories>
            </food>
            <food>
                <name>Palačinky</name>
                <price currency="CZK">100</price>
                <description>Palačinky s vanilkovou zmrzlinou a kousky ovoce</description>
                <alergens>
                    <alergen number="1">
                        <contains>Lepek</contains>
                    </alergen>
                    <alergen number="7">
